name: instagram_clone
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-139.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.7.1
  get_it: ^7.6.2
  http: ^1.1.0
  freezed_annotation: ^2.4.1
  connectivity_plus: ^4.0.2
  dart_ipify: ^1.1.1
  auto_route: ^7.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
